version: '3'

services:
  database:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - ./../etc/volumes/db:/var/lib/postgresql/data
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ecommerce
    ports:
      - 3306:3306
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
