apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  selector:
    matchLabels:
      app: ecommerce-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
        - name: ecommerce-app
          image: ecommerce
          envFrom:
            - configMapRef:
                name: general-cm
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-test-service
spec:
  selector:
    app: ecommerce-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer